openapi: 3.1.0
info:
  title: Card Game API
  version: 0.1.0
paths:
  /hello:
    get:
      operationId: getHello
      parameters:
      - name: name
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
        '400':
          description: 'Invalid value for: query parameter name'
          content:
            text/plain:
              schema:
                type: string
  /card:
    get:
      operationId: getCard
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'
  /hand:
    get:
      operationId: getHand
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hand'
  /draw:
    get:
      operationId: getDraw
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hand'
components:
  schemas:
    Card:
      title: Card
      type: object
      required:
      - rank
      - suit
      - hidden
      properties:
        rank:
          $ref: '#/components/schemas/CardRank'
        suit:
          $ref: '#/components/schemas/CardSuit'
        hidden:
          type: boolean
    CardRank:
      title: CardRank
      type: string
      enum:
      - Ace
      - Eight
      - Five
      - Four
      - Jack
      - King
      - Nine
      - Queen
      - Seven
      - Six
      - Ten
      - Three
      - Two
    CardSuit:
      title: CardSuit
      type: string
      enum:
      - Clubs
      - Diamonds
      - Hearts
      - Spades
    Hand:
      title: Hand
      type: object
      properties:
        cards:
          type: array
          items:
            $ref: '#/components/schemas/Card'
    HelloResponse:
      title: HelloResponse
      type: object
      required:
      - message
      properties:
        message:
          type: string
